require:
  - rubocop-rails
  - rubocop-capybara

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'

# 各クラスやモジュールにコメントが記述されていることをチェックしない
Style/Documentation:
  Enabled: false

# 日本語がlocaleファイル以外に記述されていることをチェックしない
Rails/I18nLocaleTexts:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Exclude:
    - 'app/controllers/sessions_controller.rb'

Metrics/MethodLength:
  Exclude:
    - 'db/**/*'
